### ISSUE TITLE
[CLOUD] Can not read config: open /root/conf/clouds.json: no such file or directory

### ISSUE THREAD

**Issue by cdupont** [Waziup/wazigate-edge#3]
After a reinstall, I lost my clouds.json.
I would be nice to have a default file in the github.

**Comment by j-forster** [comment]
There are default files for clouds.json:
This repo offers a cloud.json that points to Wazihub (with no credentials) by default, see https://github.com/Waziup/wazigate-edge/blob/master/clouds.json

The waziup-gateway repo uses a clouds.json that points to Wazihub with the guest credentials, see https://github.com/Waziup/waziup-gateway/blob/master/setup/clouds.json
